# Compile exact production function bodies without unrelated gameplay linkage.
# Like extract_menu_config.cmake, changes to originals force regeneration.
function(session_extract file start end output)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/${file}")
    file(READ "${PROJECT_SOURCE_DIR}/${file}" source)
    string(FIND "${source}" "${start}" begin)
    if(end STREQUAL "EOF")
        string(LENGTH "${source}" finish)
    else()
        string(FIND "${source}" "${end}" finish)
    endif()
    if(begin LESS 0 OR finish LESS begin)
        message(FATAL_ERROR "Cannot locate production session test body: ${file}: ${start}")
    endif()
    math(EXPR length "${finish} - ${begin}")
    string(SUBSTRING "${source}" ${begin} ${length} body)
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${output}" "${body}")
endfunction()
session_extract(Hunt/Game/EngineInit.cpp "void SetupRes()" "void EnumerateResolutions()" session_resolution.inc)
session_extract(Hunt/Game/EngineInit.cpp "static std::string GetConfigPath()" EOF session_config.inc)
session_extract(Hunt/Game/Trophy.cpp "void LoadTrophy2(int RegNumber)" EOF session_trophy.inc)
session_extract(Hunt/Loaders/Resources.cpp "void SaveScreenShot()" EOF session_output.inc)
session_extract(Hunt/Game/Interface.cpp "void DoHalt(const char* Mess)" "void WaitRetrace()" session_exit.inc)
session_extract(Hunt/Loaders/Resources.cpp "void CreateLog()" EOF session_logs.inc)
