// Exact production bodies, regenerated by CMake, not test reimplementations.
#include "Hunt.h"
#include "Session/Session.h"
#include "Platform/Screenshot.h"
#include "Game/ProfileSerialization.h"
#include "Core/ConfigText.h"
#include "Game/RefreshPreference.h"
#include "Game/ResolutionSelection.h"
#include <fstream>
#include <cerrno>
#include "session_resolution.inc"
#include "session_config.inc"
#include "session_trophy.inc"
#include "session_output.inc"
void SessionTestCreateConfig() { CreateDefaultConfig(); }
void SessionTestLoadConfig() { LoadConfig(); }
