<#
.SYNOPSIS
  Builds the Carnivores 2 MEE Modernized release zip (version from Version.h).

.DESCRIPTION
  Assembles the package folder (pkg/Carnivores2_MEE_v<Version>_Modernized)
  from the shipping build outputs, the runtime OpenAL Soft files, a
  generated clean default config.cfg, the MIT/LGPL license texts, the
  end-user README.txt and CHANGELOG, and produces the versioned zip.

  The game exe is distributed under its classic MEE names (v_gl.ren /
  v_soft.ren) because the menu launches those names (Menu/Menu.cpp).

  Requires the shipping builds to exist (see release-guide.md 5.1).
  The ogl-release-shipping tree supplies both the menu and GL engine;
  soft-release supplies the software engine. menu-release is a separate tree.

.EXAMPLE
  powershell -NoProfile -File tools/release/make-c2-package.ps1
#>
[CmdletBinding()]
param(
    [string]$RepoRoot = '',
    [string]$PkgRoot  = '',
    [string]$OpenAlDir = '',          # dir containing OpenAL32.dll + alsoft.ini (from a game install)
    [string]$SevenZipPath = '',       # path to 7z.exe (auto-detected if empty)
    [string]$LgplPath = '',           # path to LGPL 2.1 license text (fetched if empty)
    [string]$ShaOut = ''
)

$ErrorActionPreference = 'Stop'
if (-not $RepoRoot) { $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path }
if (-not $PkgRoot)  { $PkgRoot  = Join-Path $RepoRoot 'pkg' }
if (-not $ShaOut)   { $ShaOut   = Join-Path $PkgRoot 'SHA256.txt' }
# Read the shared executable version to keep archive and binary labels aligned.
$versionHeader = Get-Content (Join-Path $RepoRoot 'Hunt\Core\Version.h') -Raw
if ($versionHeader -notmatch '#define\s+VERSION_STRING\s+"(\d+\.\d+\.\d+)\.0"') {
    throw 'Expected VERSION_STRING in major.minor.patch.0 format'
}
$Version = $Matches[1]
$ZipName   = "Carnivores2_MEE_v${Version}_Modernized.zip"
$PkgName   = "Carnivores2_MEE_v${Version}_Modernized"
$PkgDir    = Join-Path $PkgRoot $PkgName

# Resolve external tools without hardcoding a developer's machine paths:
#  - 7-Zip: search common install locations / PATH
#  - OpenAL runtime: caller must supply -OpenAlDir (a stock game folder), since
#    the DLLs are not redistributable from this repo
#  - LGPL text: fetch from the official OpenAL-Soft source once (cached), so no
#    repo copy of the license is needed and no local path is embedded
if (-not $SevenZipPath) {
    $candidates = @(
        "$env:ProgramFiles\7-Zip\7z.exe",
        "${env:ProgramFiles(x86)}\7-Zip\7z.exe",
        "$env:LOCALAPPDATA\Programs\7-Zip\7z.exe"
    ) | Where-Object { Test-Path $_ }
    $cmd7z = Get-Command 7z.exe -ErrorAction SilentlyContinue
    $SevenZipPath = if ($candidates) { $candidates[0] } elseif ($cmd7z) { $cmd7z.Source }
}
if (-not $SevenZipPath) { throw '7z.exe not found - pass -SevenZipPath or install 7-Zip' }

if (-not $LgplPath) {
    $LgplPath = Join-Path $PkgRoot 'COPYING.OpenAL-Soft.txt'
    if (-not (Test-Path $LgplPath)) {
        Write-Host 'Fetching LGPL 2.1 license text (OpenAL-Soft official copy)...'
        Invoke-WebRequest -UseBasicParsing -Uri 'https://raw.githubusercontent.com/kcat/openal-soft/master/COPYING' -OutFile $LgplPath
    }
}

if (-not $OpenAlDir) { throw 'Pass -OpenAlDir pointing at a folder containing OpenAL32.dll and alsoft.ini (e.g. a stock Carnivores 2 install)' }
$SevenZip  = $SevenZipPath
$lgpl      = $LgplPath

# --- inputs -------------------------------------------------------------
$menuExe = Join-Path $RepoRoot 'build\ogl-release-shipping\bin\Carnivores2Menu.exe'
$glExe   = Join-Path $RepoRoot 'build\ogl-release-shipping\bin\Carnivores1_GL.exe'
$softExe = Join-Path $RepoRoot 'build\soft-release\bin\Carnivores1_SOFT.exe'
$shaders = Join-Path $RepoRoot 'build\ogl-release-shipping\bin\shaders'
$openal  = Join-Path $OpenAlDir 'OpenAL32.dll'
$alsoft  = Join-Path $OpenAlDir 'alsoft.ini'
# A clean default config is generated by the engine on first launch; we ship
# the same content. The deployed config.cfg is dev-tweaked - never ship it.
$engineCfg = Join-Path $RepoRoot 'Hunt\Game\EngineInit.cpp'

foreach ($f in @($menuExe, $glExe, $softExe, $openal, $alsoft, $lgpl, $engineCfg)) {
    if (-not (Test-Path $f)) { throw "Missing required file: $f" }
}
if (-not (Test-Path $shaders)) { throw "Missing shaders dir: $shaders" }

# --- clean staging ------------------------------------------------------
if (Test-Path $PkgDir) { Remove-Item $PkgDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path $PkgDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $PkgDir 'THIRD-PARTY-LICENSES') | Out-Null

# --- binaries -----------------------------------------------------------
Copy-Item $menuExe $PkgDir
# game exes go under their classic MEE names (the menu launches these)
Copy-Item $glExe   (Join-Path $PkgDir 'v_gl.ren')
Copy-Item $softExe (Join-Path $PkgDir 'v_soft.ren')
Copy-Item -Recurse -Force $shaders (Join-Path $PkgDir 'shaders')
Copy-Item $openal  $PkgDir
Copy-Item $alsoft  $PkgDir
Copy-Item (Join-Path $RepoRoot 'LICENSE')   $PkgDir
Copy-Item (Join-Path $RepoRoot 'NOTICE.md') $PkgDir
Copy-Item (Join-Path $RepoRoot 'CHANGELOG.md') $PkgDir
Copy-Item $lgpl (Join-Path $PkgDir 'THIRD-PARTY-LICENSES\COPYING.OpenAL-Soft.txt')

# --- clean default config.cfg ------------------------------------------
# Mirror Hunt/Game/EngineInit.cpp CreateDefaultConfig (fov 62 default,
# object_detail 48 default, fps_limit 1, verbose_logging 0,
# nightvision_key 78, glperf_logging 0, commented audio/hunt examples).
# Keep this in sync with the source.
@"
# Carnivores 2 Modder's Engine - Configuration
# This file is auto-generated on first launch.
# Edit values as needed - they are validated on load.
#
# The menu updates the settings it owns when you change them.
# Comments and other keys (including audio overrides) are preserved.

# Renderer: 0=Software, 1=OpenGL (default: 1)
renderer 1

# Field of view in degrees (default: 62, range: 35-90)
fov 62

# Object detail / view distance (default: 48, range: 24-96)
object_detail 48

# FPS limit: 0=Unlimited, 1=60, 2=120, 3=240 (default: 1)
fps_limit 1

# Verbose logging: 0=off, 1=on (default: 0)
verbose_logging 0

# Nightvision key VK code (default: 78 = 'N')
nightvision_key 78

# Window resolution, e.g. 1920x1080. Overrides the per-profile
# resolution saved in trophy0N.sav. Omit to use the profile value.
# The menu writes this automatically when you change Resolution.
#resolution 1920x1080

# Display mode: 0=windowed, 1=exclusive fullscreen, 2=borderless
# fullscreen (default: 2). The menu writes this when you change the
# Display Mode video option.
display_mode 2

# Exclusive-fullscreen refresh rate.
# 0=automatic; integer Hz or exact fraction such as 60000/1001.
refresh_rate 0

# GPU features bitmask (default: all optimizations enabled)
# Set to 0 to disable all GPU optimizations.
gpufeatures 4294967295

# GL performance logging: 0=off, 1=on (default: 0)
# Requires GL_PERF_HOOKS build. Writes glperf-*.log files.
glperf_logging 0

# Audio reverb tuning (OpenAL EFX only; restart the game to apply).
# envN: 0=Generic, 1=Plate, 2=Forest, 3=Mountain, 4=Canyon,
# 5=Cave, 6=Special-1, 7=intentional no-op, 8=Underwater.
# decay: seconds [0.1,20]; decayhf: HF decay ratio [0.1,2];
# diffusion: [0,1]; reverb: late-reverb level in mB [-10000,0].
# Uncomment to override; commented lines use compiled defaults
# (Generic: decay=1.49, decayhf=0.3, diffusion=0.4, reverb=-620).
#env0_decay 1.49
#env0_decayhf 0.3
#env0_diffusion 0.4
#env0_reverb -620

# Last hunt setup (written by the menu when you launch a hunt).
# The menu reselects these on the hunt screen; delete them to
# return to entry defaults.
"@ | Set-Content -Path (Join-Path $PkgDir 'config.cfg') -Encoding Ascii

# --- end-user README.txt ------------------------------------------------
@"
================================================================
  Carnivores 2 - Modder's Engine v1.11 (Modernized v$Version)
================================================================

VERSIONING
  Project release Modernized v$Version = GitHub v$Version-modernized.
  Upstream Modder's Engine v1.11 is the base; modernization releases
  are numbered separately. V5 is only the ModDB download label.
  Windows executable version: $Version.0

WHAT'S INCLUDED
  Carnivores2Menu.exe - Launcher / settings menu (entry point)
  v_gl.ren            - OpenGL 3.3 renderer (launched by menu)
  v_soft.ren          - Software renderer (launched by menu)
  shaders/            - GL shader programs
  config.cfg          - Default configuration
  CHANGELOG.md        - Full V5 and previous release notes
  OpenAL32.dll        - OpenAL Soft runtime (audio)
  alsoft.ini          - OpenAL configuration for this game
  LICENSE, NOTICE.md, THIRD-PARTY-LICENSES/ - legal texts

REQUIREMENTS
  - Windows PC (32-bit / x86)
  - OpenGL 3.3 capable GPU for the GL renderer
  - Original game installation (HUNTDAT folder with game assets)
  - Microsoft Visual C++ Redistributable 2019-2022 (x86)

INSTALLATION
  1. Use your compatible original game/mod installation.
     Back up config.cfg and saves before updating.
  2. Copy the files INSIDE the extracted package folder into the
     game folder next to HUNTDAT. Keep your existing config.cfg
     when updating if you want to preserve personal settings.
  3. Launch Carnivores2Menu.exe.

NIGHT VISION (modders)
  Night vision is added by this modernization and works on every
  game/mod data set. If your HUNTDAT has no night-vision art, the
  shop row shows without an icon (and uses a built-in description).
  To add your own art/description, drop these into your HUNTDAT:
    HUNTDAT/menu/pics/equip_nv.tga   - shop icon (16-bit TGA)
    HUNTDAT/menu/txt/nightvis.nfo    - description text
  When present they are used automatically.

LEGAL
  This package contains MODIFIED EXECUTABLES and supporting
  libraries. It does NOT include any original game assets. You
  MUST own the original game to use this mod. Assets are
  copyrighted by their owners and are NOT redistributed.
  See LICENSE (MIT) and NOTICE.md. OpenAL Soft is distributed
  under the LGPL - see THIRD-PARTY-LICENSES/ and
  https://openal-soft.org/

UPSTREAM CREDITS
  Built on Modder's Edition Engine by Ornithomimid1 (Oli) and
  upstream contributors. Original Carnivores 2 by Action Forms.
  https://github.com/Ornithomimid1
  https://github.com/carnivores-cpe/Carnivores-CPE/tree/Map-Amb-Demo-2
  See NOTICE.md for this fork's exact base snapshot and menu credits.

MODERNIZED v$Version HIGHLIGHTS (since v1.1.7; ModDB label V5)
  - Trophy room finished: kills mount as static exhibits, collisions
    and hunt-info plaques restored, removal and exit handling fixed.
  - Default Run key works on fresh saves (side-aware modifier keys);
    toggle actions no longer retrigger on key auto-repeat.
  - config.cfg NUL padding no longer truncates settings: the chosen
    FPS limit now applies and effective values are logged at startup.
  - World depth stays coherent under viewmodels; unity-magnification
    red-dot sights no longer trigger the scope-mask treatment.
  - Menu: area6.map fallback for the sixth slot; ambient music keeps
    playing across submenus.
  See CHANGELOG.md for full notes and audio tuning limitations.

REPORTING ISSUES
  https://github.com/Tibbee/carnivores2-mee-modernized/issues
  Include Modernized v$Version (ModDB V5), your mod/map, renderer,
  and reproduction steps.
"@ | Set-Content -Path (Join-Path $PkgDir 'README.txt') -Encoding Ascii

# --- zip ----------------------------------------------------------------
$zipPath = Join-Path $PkgRoot $ZipName
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Push-Location $PkgRoot
try {
    & $SevenZip a -tzip -bd $ZipName "$PkgName\" | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "7z failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

# --- SHA-256 (portable; Get-FileHash may be absent on stripped PS 5.1) --
$sha = [System.BitConverter]::ToString(
    [System.Security.Cryptography.SHA256]::Create().ComputeHash(
        [System.IO.File]::OpenRead($zipPath))).Replace('-', '').ToLower()
"$sha  $ZipName" | Set-Content -Path $ShaOut -Encoding Ascii

Write-Host "Created: $zipPath"
Write-Host "SHA-256: $sha"
