#!/usr/bin/env python3
"""Pin Python 3.12 / Unicode 15.0.0 case and whitespace semantics for validation.

Data is derived from CPython's Unicode database (Unicode Data Files license;
https://www.unicode.org/license.txt). No locale or host C library is involved.
Sigma-context probes recover Cased and Case_Ignorable used by str.lower().
Run --check under the pinned Python/Unicode version to verify exact bytes.
"""
import argparse
from pathlib import Path
import unicodedata

def generate():
    if unicodedata.unidata_version != '15.0.0':
        raise SystemExit('generation requires Unicode 15.0.0 (CPython 3.12)')
    out = ['// Generated by tools/generate_schema_unicode.py; Unicode 15.0.0.\n',
           'struct CaseEntry { char32_t code; const char32_t* text; };\n']
    for name, transform in [('lower',str.lower),('fold',str.casefold)]:
        out.append(f'static const CaseEntry {name}_table[] = {{\n')
        for cp in range(0x110000):
            c=chr(cp); t=transform(c)
            if t!=c:
                escaped=''.join('\\U%08x'%ord(x) for x in t)
                out.append(f'{{0x{cp:x}, U"{escaped}"}},\n')
        out.append('};\n')
    for name,pred in [('space',str.isspace),('cased',lambda c:(c+'Σ').lower().endswith('ς')),
                      ('ignorable',lambda c:('AΣ'+c).lower()[1]=='ς' and ('AΣ'+c+'A').lower()[1]=='σ')]:
        ranges=[]; start=None; end=None
        for cp in range(0x110000):
            if pred(chr(cp)):
                if start is None:start=cp
                end=cp
            elif start is not None:ranges.append((start,end));start=None
        if start is not None:ranges.append((start,end))
        out.append(f'static const Range {name}_ranges[] = {{\n')
        out.extend(f'{{0x{a:x},0x{b:x}}},\n' for a,b in ranges)
        out.append('};\n')
    return ''.join(out)

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'native/src/schema_unicode.inc'
    data=generate()
    if args.check:
        if path.read_text()!=data:raise SystemExit('Unicode tables differ')
    else:path.write_text(data)
