#!/usr/bin/env python3
"""Unicode 15.0 decimal digits for Python profile filename regex/int semantics.

Derived from CPython Unicode data; see native/src/UNICODE-LICENSE.txt.
"""
import argparse
from pathlib import Path
import unicodedata


def generate():
    if unicodedata.unidata_version != '15.0.0':
        raise SystemExit('generation requires Unicode 15.0.0 (CPython 3.12)')
    starts = [cp for cp in range(0x110000) if unicodedata.decimal(chr(cp), -1) == 0]
    assert all(unicodedata.decimal(chr(cp + i)) == i for cp in starts for i in range(10))
    assert sum(chr(cp).isdecimal() for cp in range(0x110000)) == 10 * len(starts)
    return ('// Generated by tools/generate_profile_unicode.py; Unicode 15.0.0.\n'
            'static constexpr char32_t decimal_starts[] = {\n' +
            ''.join(f'    0x{cp:x},\n' for cp in starts) + '};\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / 'native/src/profile_unicode.inc'
    data = generate()
    if args.check:
        if path.read_text() != data:
            raise SystemExit('Profile Unicode table differs')
    else:
        path.write_text(data)
